import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Navbar from "./Navbar";
import DynamicBackground from "./DynamicBackground";
import BackToTop from "./BackToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI-EditPro - Free JSON Beautifier & Online File Converter | 17+ Developer Tools",
  description: "Free online JSON Beautifier, Formatter, Validator & Minifier with syntax highlighting. Convert PDF to DOCX, DOC, XLSX, PPTX instantly. Free Base64 encoder/decoder, URL encoder/decoder, Hash generator (MD5, SHA256, SHA512), Password generator, Word counter, JWT decoder, UUID generator, Regex tester & 17+ developer tools. No sign-up required. Fast, accurate, secure.",
  keywords: [
    // JSON Converter & Formatter - PRIMARY KEYWORDS
    "JSON beautifier",
    "JSON formatter",
    "JSON minifier",
    "JSON validator",
    "JSON parser",
    "JSON viewer",
    "JSON editor",
    "JSON prettier",
    "JSON compressor",
    "JSON decompressor",
    "JSON online",
    "JSON to CSV",
    "JSON to XML",
    "JSON to YAML",
    "JSON to Excel",
    "JSON to TSV",
    "JSON viewer online",
    "JSON formatter online",
    "JSON beautifier online",
    "format JSON",
    "pretty print JSON",
    "minify JSON",
    "compress JSON",
    "validate JSON online",
    "parse JSON online",
    "JSON lint",
    "JSON syntax checker",
    "JSON error checker",
    "JSON pretty printer",
    "JSON string formatter",
    "JSON object formatter",
    "JSON array formatter",
    "JSON converter",
    "JSON toolkit",
    "JSON utilities",
    "free JSON beautifier",
    "JSON prettifier",
    "online JSON tools",
    "JSON beautify online",
    "format JSON online",
    "JSON pretty print online",
    "JSON lint online",
    "JSON formatter free",
    "best JSON beautifier",
    "JSON viewer tool",
    "JSON editor online",
    "JSON cleaner online",
    "JSON sorter online",
    "JSON query tool",
    "JSON path finder",
    "JSON schema validator",
    "JSON to CSV online",
    "JSON to XML online",
    "JSON to YAML online",
    "JSON online converter",
    "JSON escape online",
    "JSON unescape online",
    "JSON sorter online",
    "JSON filter tool",
    "JSON diff tool",
    "JSON compare tool",
    "JSON merge tool",
    "JSON split tool",
    "JSON join tool",
    "JSON to table",
    "JSON to spreadsheet",
    "JSON pretty formatter",
    "JSON compact formatter",
    "JSON human readable",
    "JSON readable format",
    "JSON indented format",
    "JSON minified format",
    "JSON pretty print free",
    "JSON formatter without ads",
    "JSON beautifier no download",
    "JSON formatter instant",
    "JSON beautifier fast",
    "JSON formatter accurate",
    "JSON beautifier reliable",
    "JSON formatter secure",
    "JSON beautifier private",
    "JSON formatter local",
    "JSON beautifier browser",
    "JSON formatter client-side",
    "JSON beautifier no upload",
    "JSON formatter works offline",
    "JSON beautifier no account",
    "JSON beautifier no signup",
    "JSON beautifier no registration",
    "JSON beautifier free tool",
    "JSON formatter developer tool",
    "JSON beautifier web tool",
    "JSON formatter coding tool",
    "JSON beautifier programming tool",
    "JSON beautifier utility",
    "JSON beautifier online utility",
    "format JSON online tool",
    "JSON beautifier browser tool",
    "JSON beautifier web app",

    // PDF Converter Keywords
    "PDF to DOCX",
    "PDF to Word",
    "PDF to DOC",
    "PDF to XLSX",
    "PDF to Excel",
    "PDF to PPTX",
    "PDF to PowerPoint",
    "PDF to HTML",
    "PDF to TXT",
    "PDF to EPUB",
    "PDF to RTF",
    "convert PDF to DOCX",
    "convert PDF to Word",
    "PDF converter online",
    "free PDF to DOCX converter",
    "PDF to DOCX free",
    "convert PDF online",
    "PDF converter free",
    "online PDF converter",
    "PDF to Word online",
    "PDF to Excel online",
    "PDF to PowerPoint online",
    "document converter online",
    "free document converter",
    "convert PDF to DOC online",
    "PDF to DOCX converter online",
    "PDF to Word converter free",
    "PDF to Excel converter free",
    "convert PDF to XLSX online",
    "PDF to PowerPoint converter free",
    "convert PDF to PPTX online",
    "PDF to HTML converter",
    "PDF to TXT converter",
    "PDF to RTF converter",
    "PDF to EPUB converter",
    "PDF document converter",
    "batch PDF converter",
    "PDF to DOCX batch",
    "PDF format converter",
    "convert PDF to Word without email",
    "convert PDF online no download",
    "PDF to editable Word",
    "PDF to editable DOCX",
    "PDF to spreadsheet Excel",
    "PDF to presentation PowerPoint",
    "PDF to web HTML",
    "PDF to text TXT",
    "PDF to ebook EPUB",
    "PDF to rich text RTF",

    // File Converter & Document Tools
    "file converter online",
    "document converter free",
    "online file format converter",
    "DOCX to PDF",
    "DOC to PDF",
    "XLSX to PDF",
    "Excel to PDF",
    "PPTX to PDF",
    "PowerPoint to PDF",
    "TXT to PDF",
    "RTF to PDF",
    "EPUB to PDF",
    "HTML to PDF",
    "convert DOCX to PDF",
    "convert XLSX to PDF",
    "convert PPTX to PDF",
    "convert HTML to PDF",
    "DOCX converter online",
    "Excel converter online",
    "PowerPoint converter online",
    "TXT converter online",
    "RTF converter online",
    "EPUB converter online",
    "file format converter online",
    "document format converter",
    "batch file converter",
    "bulk file converter",
    "online document converter",
    "convert files online",
    "multi format converter",
    "universal file converter",
    "all file converter",
    "any file converter",
    "convert any file online",
    "free file format converter",
    "best file converter online",
    "instant file converter",
    "fast file converter",
    "accurate file converter",
    "reliable file converter",
    "secure file converter",
    "private file converter",
    "no registration file converter",

    // Developer Tools Keywords
    "Base64 encoder",
    "Base64 decoder",
    "Base64 encode",
    "Base64 decode",
    "Base64 to text",
    "text to Base64",
    "Base64 converter online",
    "Base64 encode online",
    "Base64 decode online",
    "Base64 tool online",
    "Base64 encoder online",
    "Base64 decoder online",
    "encode Base64 online",
    "decode Base64 online",
    "Base64 image encoder",
    "Base64 file encoder",
    "Base64 string encoder",
    "Base64 URL encoder",
    "Base64 hash encoder",
    "free Base64 encoder",
    "free Base64 decoder",
    "Base64 encoder no download",
    "Base64 decoder no download",
    "Base64 encoder online tool",
    "Base64 decoder online tool",

    "URL encoder",
    "URL decoder",
    "URL encode online",
    "URL decode online",
    "encode URL",
    "decode URL",
    "URL encoding online",
    "URL decoding online",
    "special characters encoder",
    "URL slug generator",
    "URL query encoder",
    "URL component encoder",
    "URL parameter encoder",
    "percent encoding online",
    "URL encoding tool",
    "URL decoding tool",
    "URL encode decode",
    "URL encode/decoder",
    "URL special characters",
    "encode special characters URL",
    "URL encoding decoder online",
    "free URL encoder",
    "free URL decoder",

    "JWT decoder",
    "JWT token decoder",
    "decode JWT online",
    "JWT parser",
    "JWT viewer",
    "JWT inspector",
    "JWT analyzer",
    "JWT reader",
    "JWT tool online",
    "decode JWT token online",
    "JWT payload decoder",
    "JWT header decoder",
    "JWT signature verifier",
    "JWT claims decoder",
    "JWT expiration checker",
    "JWT decoder online free",
    "parse JWT online",
    "view JWT online",
    "inspect JWT online",
    "decode JWT without secret",
    "JWT decoder without signature verification",
    "JWT online utility",

    "Hash generator",
    "MD5 hash generator",
    "SHA256 hash generator",
    "SHA512 hash generator",
    "SHA1 hash generator",
    "generate hash online",
    "online hash generator",
    "create hash online",
    "hash maker online",
    "generate MD5 online",
    "generate SHA256 online",
    "generate SHA512 online",
    "text to MD5",
    "text to SHA256",
    "password hash generator",
    "file hash generator",
    "string hash generator",
    "hash calculator online",
    "hash function online",
    "hashing tool online",
    "MD5 hash online",
    "SHA256 hash online",
    "SHA512 hash online",
    "MD5 checksum generator",
    "SHA256 checksum generator",
    "free hash generator",
    "online hashing tool",
    "generate hash from text",
    "hash generator free",
    "text hashing tool",
    "file hashing tool",

    "UUID generator",
    "generate UUID online",
    "UUID generator online",
    "create UUID online",
    "random UUID generator",
    "UUID v4 generator",
    "UUID v1 generator",
    "unique ID generator",
    "GUID generator",
    "generate GUID online",
    "UUID maker online",
    "UUID creator online",
    "UUID generator free",
    "UUID generator no download",
    "online UUID creator",
    "UUID random generator",
    "UUID generator tool",
    "unique identifier generator",
    "generate unique ID online",
    "random ID generator online",
    "UUID generator utility",
    "UUID generator API",

    "Password generator",
    "generate password online",
    "random password generator",
    "secure password generator",
    "strong password generator",
    "password maker online",
    "create password online",
    "password generator tool",
    "secure password maker",
    "complex password generator",
    "custom password generator",
    "password generator with symbols",
    "password generator with numbers",
    "password generator with letters",
    "generate random password",
    "random password maker",
    "password generator free",
    "online password generator",
    "best password generator",
    "secure random password",
    "strong random password",
    "password generator no download",
    "password generator online tool",
    "generate secure password online",
    "create strong password online",
    "password generator client-side",
    "password generator browser-based",
    "password generator offline",
    "password generator no server",
    "local password generator",

    "Word counter",
    "character counter",
    "word count online",
    "character count online",
    "count words online",
    "count characters online",
    "word counter online",
    "character counter online",
    "text word counter",
    "text character counter",
    "online word counter",
    "online character counter",
    "free word counter",
    "free character counter",
    "word count tool online",
    "character count tool online",
    "text analyzer online",
    "word frequency counter",
    "sentence counter online",
    "paragraph counter online",
    "count words in text",
    "count characters in text",
    "word counter with spaces",
    "word counter without spaces",
    "unicode character counter",
    "word count PDF online",
    "word count DOCX online",
    "word count tool free",
    "character count tool free",
    "text statistics tool",

    "Text compare",
    "text diff",
    "compare text online",
    "diff text online",
    "text comparison tool",
    "text diff checker",
    "compare two texts online",
    "text difference finder",
    "find text differences",
    "text comparison online",
    "online text comparison",
    "text compare tool",
    "diff tool online",
    "text merge tool",
    "side by side text compare",
    "highlight text differences",
    "visual text diff",
    "text comparator online",
    "compare documents online",
    "text comparison utility",
    "diff checker online",
    "text diff tool free",
    "online text diff",
    "compare text differences",
    "text comparison service",
    "text similarity checker",
    "text match finder",

    "Regex tester",
    "regular expression tester",
    "regex tester online",
    "test regex online",
    "regex validator",
    "regex checker online",
    "regex pattern tester",
    "regex builder online",
    "regex tester with flags",
    "regex match tester",
    "regex generator",
    "regex debugger online",
    "PCRE tester online",
    "JavaScript regex tester",
    "regex playground online",
    "regular expression validator",
    "regex expression tester",
    "online regex tester tool",
    "regex tester utility",
    "regex testing tool online",
    "test regular expression online",
    "verify regex online",
    "regex pattern validator",
    "regex online editor",
    "regex match checker",
    "regex find tester",
    "regex replace tester",
    "regex search tester",

    // Color Tools
    "Color picker",
    "hex to RGB",
    "RGB to hex",
    "color converter",
    "color code converter",
    "color format converter",
    "RGB to hex converter",
    "hex to RGB converter",
    "RGB to HSL",
    "HSL to RGB",
    "color code generator",
    "color palette generator",
    "color picker online",
    "online color picker",
    "color converter online",
    "convert color codes",
    "color code tool online",
    "hex color picker",
    "RGB color picker",
    "HSL color picker",
    "color code calculator",
    "color code transformer",
    "free color picker",
    "online color tool",
    "color code picker",
    "web color converter",
    "color format picker",
    "color value converter",
    "color name converter",
    "color picker browser",
    "color picker utility",

    // Timestamp & Time Tools
    "Unix timestamp converter",
    "epoch converter",
    "timestamp to date",
    "date to timestamp",
    "convert Unix timestamp",
    "convert epoch time",
    "Unix time converter",
    "epoch time converter",
    "timestamp converter online",
    "Unix timestamp online",
    "epoch timestamp online",
    "date timestamp converter",
    "time converter Unix",
    "Unix epoch converter",
    "timestamp calculator online",
    "convert time to timestamp",
    "Unix timestamp calculator",
    "epoch time calculator",
    "timestamp generator online",
    "current Unix timestamp",
    "Unix time now",
    "timestamp now online",
    "Unix timestamp decoder",
    "epoch decoder online",
    "timestamp decoder online",
    "Unix timestamp validator",
    "epoch validator online",
    "timestamp parser online",
    "parse timestamp online",

    // Markdown Tools
    "Markdown editor",
    "Markdown previewer",
    "Markdown to HTML",
    "Markdown converter",
    "Markdown parser online",
    "Markdown renderer online",
    "Markdown preview online",
    "edit Markdown online",
    "write Markdown online",
    "Markdown editor online",
    "Markdown viewer online",
    "Markdown formatter online",
    "Markdown beautifier online",
    "convert Markdown to HTML online",
    "Markdown to HTML converter online",
    "Markdown editor with preview",
    "live Markdown editor",
    "Markdown preview tool",
    "Markdown HTML converter",
    "Markdown to web converter",
    "Markdown online editor",
    "Markdown processor online",
    "Markdown compiler online",
    "Markdown translator online",
    "Markdown generator online",
    "Markdown creator online",
    "Markdown writer online",
    "Markdown markdown",
    "GitHub Markdown editor",
    "Markdown editor free",

    // Text & Code Formatters
    "HTML formatter",
    "CSS formatter",
    "XML formatter",
    "SQL formatter",
    "JavaScript formatter",
    "JSON formatter",
    "YAML formatter",
    "format code online",
    "format HTML online",
    "format CSS online",
    "format XML online",
    "format SQL online",
    "format JavaScript online",
    "format JSON online",
    "format YAML online",
    "code beautifier online",
    "HTML beautifier online",
    "CSS beautifier online",
    "XML beautifier online",
    "SQL beautifier online",
    "JavaScript beautifier online",
    "JSON beautifier online",
    "YAML beautifier online",
    "indent code online",
    "format code online tool",
    "code formatter free",
    "online code formatter",
    "code beautifier free",
    "format code without download",
    "online code beautifier",

    // CSV & Data Tools
    "CSV formatter",
    "CSV viewer",
    "CSV to JSON",
    "CSV to Excel",
    "CSV parser online",
    "CSV converter online",
    "format CSV online",
    "CSV beautifier online",
    "CSV minifier online",
    "CSV compressor online",
    "CSV to table online",
    "CSV data viewer",
    "CSV online viewer",
    "CSV file viewer online",
    "CSV preview online",
    "CSV reader online",
    "CSV data formatter",
    "CSV structure viewer",
    "CSV columns viewer",
    "CSV row counter",
    "CSV column counter",
    "CSV data analyzer",
    "CSV to HTML table",
    "CSV to JSON converter online",
    "convert CSV to JSON online",
    "CSV to Excel online",
    "CSV formatter tool online",
    "CSV parser tool online",
    "CSV viewer tool online",
    "CSV converter tool online",

    // Additional Keywords
    "developer tools",
    "online developer tools",
    "web developer tools",
    "free developer tools",
    "developer utilities",
    "web developer utilities",
    "free online tools",
    "online utilities",
    "web tools",
    "free web tools",
    "online converters",
    "online generators",
    "online encoders",
    "online decoders",
    "online calculators",
    "online checkers",
    "online testers",
    "online validators",
    "online converters free",
    "developer tools online",
    "programmer tools online",
    "coding tools online",
    "software tools online",
    "productivity tools online",
    "utility tools online",
    "browser-based tools",
    "client-side tools",
    "no-download tools",
    "no-software tools",
    "instant tools",
    "fast tools",
    "quick tools",
    "easy tools",
    "simple tools",
    "user-friendly tools",
    "intuitive tools",
    "simple to use tools",
    "one-click tools",
    "drag and drop tools",
    "upload and convert",
    "copy paste tools",
    "paste and format",
    "paste and convert",
    "paste and beautify",
    "paste and encode",
    "paste and decode",
    "paste and generate",
    "paste and analyze",
    "paste and validate",
    "paste and test",
    "paste and count",
    "paste and compare",
    "paste and edit",
    "paste and process",
    "process text online",
    "process JSON online",
    "process CSV online",
    "process XML online",
    "process HTML online",
    "process data online",
    "format data online",
    "clean data online",
    "validate data online",
    "analyze data online",
    "parse data online",
    "view data online",
    "inspect data online",
    "debug data online",
    "troubleshoot data online",
  ].join(", "),
  authors: [{ name: "AI-EditPro" }],
  creator: "AI-EditPro",
  publisher: "AI-EditPro",
  formatDetection: {
    email: true,
    address: true,
    telephone: true,
  },
  openGraph: {
    title: "AI-EditPro - Free Online File Converter & 17+ Developer Tools",
    description: "Convert PDF to DOCX, DOC, XLSX, PPTX + 17 free developer tools including JSON beautifier, password generator, word counter, color picker, Base64 encoder, Hash generator & more.",
    url: "https://AI-EditPro.net",
    siteName: "AI-EditPro",
    images: [
      {
        url: "https://AI-EditPro.net/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "AI-EditPro - Free File Converter & Developer Tools",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "AI-EditPro - Free Online File Converter & 17+ Developer Tools",
    description: "Convert any file format instantly. PDF to DOCX, JSON beautifier, password generator, word counter, color picker, Base64 encoder & more. No sign-up required.",
    images: ["https://AI-EditPro.net/og-image.jpg"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
  category: "Technology",
  alternates: {
    canonical: "https://AI-EditPro.net",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebApplication",
              name: "AI-EditPro",
              description: "Free online file converter and developer tools suite",
              url: "https://AI-EditPro.net",
              applicationCategory: "Utility",
              offers: {
                "@type": "Offer",
                price: "0",
                priceCurrency: "USD",
              },
              aggregateRating: {
                "@type": "AggregateRating",
                ratingValue: "4.9",
                ratingCount: "50000",
              },
              potentialAction: {
                "@type": "UseAction",
                target: "https://AI-EditPro.net/converter",
              },
            }),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "FAQPage",
              "mainEntity": [
                {
                  "@type": "Question",
                  "name": "Is AI-EditPro free to use?",
                  "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Yes, AI-EditPro is completely free. No sign-up or credit card required."
                  }
                },
                {
                  "@type": "Question",
                  "name": "How do I convert a PDF to DOCX?",
                  "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Go to the Converter page, upload your PDF file, select DOCX as the output format, and click Convert. Your file will be ready in seconds."
                  }
                },
                {
                  "@type": "Question",
                  "name": "What is a JSON Beautifier?",
                  "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "A JSON Beautifier formats compact or minified JSON data into a readable, indented structure. AI-EditPro's JSON Beautifier also validates JSON syntax."
                  }
                },
                {
                  "@type": "Question",
                  "name": "How do I generate a secure password?",
                  "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Use AI-EditPro's Password Generator tool. Set your desired length (up to 128 characters), choose character types (uppercase, lowercase, numbers, symbols), and click Generate."
                  }
                }
              ]
            }),
          }}
        />
        {/* Additional SEO meta tags */}
        <meta name="theme-color" content="#a78bfa" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="mobile-web-app-capable" content="yes" />
        
        {/* Preconnect to external resources */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        
        {/* Google Tag Manager */}
        <Script id="gtm-script">
          {`
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GT-K5MKQSV5');
          `}
        </Script>

        {/* Google Analytics 4 */}
        <Script async src={`https://www.googletagmanager.com/gtag/js?id=G-WM5JVFQBDG`} />
        <Script id="google-analytics">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-WM5JVFQBDG', {
              send_page_view: true,
              page_title: document.title,
              page_location: window.location.href
            });
          `}
        </Script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Google Tag Manager (noscript) */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GT-K5MKQSV5"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          />
        </noscript>

        {/* Dynamic canvas background */}
        <DynamicBackground />

        {/* Navbar */}
        <Navbar />

        {/* Page content */}
        <div style={{ position: "relative", zIndex: 1 }}>
          {children}
        </div>
        <BackToTop />
      </body>
    </html>
  );
}
